apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cat.secret.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cat.module.labels" . | nindent 4 }}
type: Opaque
stringData:
  MYSQL_PASSWORD: {{ ternary .Values.cat.mysql.rootpasswd .Values.cat.server.mysql.password .Values.cat.mysql.enabled | quote }}
