{{- if .Values.cat.mysql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cat.mysql.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cat.module.labels" . | nindent 4 }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: mysql
      port: {{ .Values.cat.mysql.port }}
      targetPort: mysql
      protocol: TCP
  selector:
    {{- include "cat.mysql.selectorLabels" . | nindent 4 }}
{{- end }}
